# --- Created by Ebean DDL
# To stop Ebean DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table tasks (
  system_task_id                bigint generated by default as identity not null,
  title                         varchar(255),
  description                   varchar(255),
  status                        varchar(255),
  due_date                      timestamp,
  due_date_str                  varchar(255),
  creation_date                 timestamp,
  creation_date_str             varchar(255),
  constraint pk_tasks primary key (system_task_id)
);

create table todo_task_comments (
  todo_task_comments_id         bigint generated by default as identity not null,
  task_comments                 varchar(255),
  creation_date                 timestamp,
  creation_date_str             varchar(255),
  systemtasksid                 bigint not null,
  constraint pk_todo_task_comments primary key (todo_task_comments_id)
);

create index ix_todo_task_comments_systemtasksid on todo_task_comments (systemtasksid);
alter table todo_task_comments add constraint fk_todo_task_comments_systemtasksid foreign key (systemtasksid) references tasks (system_task_id) on delete restrict on update restrict;


# --- !Downs

alter table todo_task_comments drop constraint if exists fk_todo_task_comments_systemtasksid;
drop index if exists ix_todo_task_comments_systemtasksid;

drop table if exists tasks;

drop table if exists todo_task_comments;

